version: "3"
services:
  postgres:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
